In [17]:
import tensorflow as tf
import numpy as  np
tf.__version__

'2.4.1'

In [10]:
my_var = tf.Variable([1, 3, 5], dtype=tf.float32)
my_var

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 3., 5.], dtype=float32)>

In [12]:
print(my_var.numpy())
my_var.assign_add([16, 16, 16])

print(my_var.numpy())

[1. 3. 5.]
[17. 19. 21.]


In [13]:
strings = tf.Variable(['Hola Hola'], dtype=tf.string)
ints = tf.Variable([2, 4, 5], dtype=tf.int32)
complexes = tf.Variable([23 - 1j, 23 - 2j], dtype=tf.complex64)

strings, ints, complexes

(<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Hola Hola'], dtype=object)>,
 <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 4, 5])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=complex64, numpy=array([23.-1.j, 23.-2.j], dtype=complex64)>)

In [14]:
tf.Variable(tf.constant(4.2, shape=(4, 4, 2)))

<tf.Variable 'Variable:0' shape=(4, 4, 2) dtype=float32, numpy=
array([[[4.2, 4.2],
        [4.2, 4.2],
        [4.2, 4.2],
        [4.2, 4.2]],

       [[4.2, 4.2],
        [4.2, 4.2],
        [4.2, 4.2],
        [4.2, 4.2]],

       [[4.2, 4.2],
        [4.2, 4.2],
        [4.2, 4.2],
        [4.2, 4.2]],

       [[4.2, 4.2],
        [4.2, 4.2],
        [4.2, 4.2],
        [4.2, 4.2]]], dtype=float32)>

In [16]:
v = tf.Variable(0.0, dtype=tf.float32)
w = v + 14  # v.assign_add(14)
w

<tf.Tensor: shape=(), dtype=float32, numpy=14.0>

In [22]:
a = tf.constant(np.arange(16), shape=(4,4))
rank = tf.rank(a)
rank

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [24]:
a2 = tf.reshape(a, shape=(8,2))
a2

<tf.Tensor: shape=(8, 2), dtype=int32, numpy=
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])>

In [26]:
ones = tf.ones((3,4))
zeros = tf.zeros((3,4))
eye = tf.eye(3)

ones, zeros, eye

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=float32)>)

In [28]:
a = tf.constant(np.random.randint(0, 255,size=(28, 28)), dtype=tf.float32)
a.shape
a = tf.expand_dims(a, axis=0)
a.shape

TensorShape([1, 28, 28])

In [30]:
a = tf.constant(np.random.random((2,4,4)), dtype=tf.float32)
print(a)


tf.Tensor(
[[[0.36365736 0.6580307  0.07227851 0.6835661 ]
  [0.9871185  0.6854033  0.8699895  0.18440615]
  [0.8780037  0.88762724 0.1536906  0.8805309 ]
  [0.05879891 0.9690797  0.255593   0.65498155]]

 [[0.73705304 0.78796864 0.33837926 0.41823936]
  [0.6092022  0.38989115 0.7441175  0.9527674 ]
  [0.42017147 0.5356519  0.8653621  0.22420391]
  [0.42794508 0.10783754 0.58948463 0.09611838]]], shape=(2, 4, 4), dtype=float32)
